"""initial

Revision ID: 6b4bfa50e56e
Revises:
Create Date: 2024-02-20 22:57:44.659190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6b4bfa50e56e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("ip", sa.VARCHAR(length=15), nullable=True),
        sa.Column("country", sa.VARCHAR(length=32), nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("refresh_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("public_id", sa.VARCHAR(length=32), nullable=False),
        sa.Column("password", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=128), nullable=False),
        sa.Column("user_salt", sa.VARCHAR(length=32), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("user_salt"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("session")
    # ### end Alembic commands ###
