version: "3"

services:
  rchat_test:
    image: ${IMAGE_NAME}
    env_file: test.env
    volumes:
      - "../../storage:/app/storage"
    networks:
      - postgres_test
      - nginx
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
    logging:
      driver: fluentd
      options:
        fluentd-address: rchat-company.ru:24224
        tag: rchat.backend

networks:
  postgres_test:
    driver: overlay
    external: true
  nginx:
    driver: overlay
    external: true

