version: '3'

services:
  nginx:
    image: nginx_test
    volumes:
      - "/apps/nginx/www:/var/www"
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: fluentd
      options:
        fluentd-address: rchat-company.ru:24224
        tag: rchat.nginx


networks:
  nginx:
    driver: host
    external: true
