FROM registry:2.7.0

COPY /certs/cert.pem /etc/docker/certs.d/rchat-company.ru:5000/cert/client.cert
COPY /certs/privkey.pem /etc/docker/certs.d/rchat-company.ru:5000/cert/client.key
COPY /certs/fullchain.pemy /etc/docker/certs.d/rchat-company.ru:5000/cert/ca.crt