name: Build backend test

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - lint
    types:
      - completed

env:
  IMAGE_NAME: ${{vars.CI_REGISTRY_HOST}}/rchat-test:${{github.SHA}}-test

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$IMAGE_NAME"
      - uses: actions/checkout@v4
      - name: Login in docker registry
        run: echo ${{vars.CI_REGISTRY_PASSWORD}} | docker login ${{vars.CI_REGISTRY_HOST}} -u ${{vars.CI_REGISTRY_USERNAME}} --password-stdin
      - name: Build image
        run: docker build -f deployments/app/Dockerfile -t $IMAGE_NAME .
      - name: Push image
        run: docker push $IMAGE_NAME
