name: build_backend_test_image

on:
  workflow_run:
    workflows: ["lint"]
    types: [completed]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login in docker registry
        uses: docker/login-action@v3
        with:
          username: ${{env.CI_REGISTRY_USERNAME}}
          password: ${{env.CI_REGISTRY_PASSWORD}}
      - name: Set up build
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: deployments/app
          file: deployments/app/Dockerfile
          push: true
          tags: ${{env.CI_REGISTRY_HOST}}/rchat-test