name: Deploy backend test

on:
  workflow_run:
    workflows:
      - Build backend test
    types:
      - completed
  workflow_dispatch:
    branches:
      - master

jobs:
  setup_ssh:
    uses: ./.github/workflows/template_deploy.yml
  deploy_backend:
    runs-on: ubuntu-latest
    needs: setup_ssh
    steps:
      - uses: actions/checkout@v4
      - name: Deploy backend
        run: docker stack deploy --compose-file deployments/app/docker-compose.test.yml --with-registry-auth --prune rchat_test

