name: Lint

on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up python
          uses: actions/setup-python@v4
          with:
              python-version: 3.11
        - run: sudo apt update
        - run: sudo apt install make -y
        - run: make venv
        - name: Lint
          run: make lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    if: {{$github.EVENT_NAME == 'workflow_dispatch' }}
    steps:
      - run: echo "Manual step"

