name: Deploy template

on:
  workflow_call:

env:
  SSH_PRIVATE_KEY: ${{vars.SSH_PRIVATE_KEY}}
  SSH_KNOWN_HOSTS: ${{vars.SSH_KNOWN_HOSTS}}

jobs:
  setup_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssh
        run: |
          eval $(ssh-agent -s)
          touch ./id_rsa
          ls .
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ./id_rsa
          chmod 400 ./id_rsa
          ssh-add "./id_rsa"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Login in docker hub
        run: |
          ssh ${{vars.DOCKER_SWARM_MASTER_SSH}}
          docker context create swarm-cluster --docker "host=ssh://${{vars.DOCKER_SWARM_MASTER_SSH}}"
          docker context use swarm-cluster
          echo ${{vars.CI_REGISTRY_PASSWORD}} | docker login ${{vars.CI_REGISTRY_HOST}} -u ${{vars.CI_REGISTRY_USERNAME}} --password-stdin
