name: Deploy template

on:
  workflow_call:

env:
  SSH_PRIVATE_KEY: ${{vars.SSH_PRIVATE_KEY}}
  SSH_PUBLIC_KEY: ${{vars.SSH_PUBLIC_KEY}}
  SSH_KNOWN_HOSTS: ${{vars.SSH_KNOWN_HOSTS}}
  SSH_KNOWN_HOSTS_OLD: ${{vars.SSH_KNOWN_HOSTS_OLD}}

jobs:
  setup_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssh
        run: |
          eval $(ssh-agent -s)
          mkdir .ssh
          touch .ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa
          touch .ssh/id_rsa.pub
          echo "$SSH_PUBLIC_KEY" > .ssh/id_rsa.pub
          chmod 400 .ssh/id_rsa
          chmod 700 .ssh
          touch .ssh/known_hosts
          touch .ssh/known_hosts.old
          echo "$SSH_KNOWN_HOSTS" > .ssh/known_hosts
          echo "$SSH_KNOWN_HOSTS_OLD" > .ssh/known_hosts.old
          chmod 644 .ssh/known_hosts
      - name: Login in docker hub
        run: |
          ssh ${{vars.DOCKER_SWARM_MASTER_SSH}}
          docker context create swarm-cluster --docker "host=ssh://${{vars.DOCKER_SWARM_MASTER_SSH}}"
          docker context use swarm-cluster
          echo ${{vars.CI_REGISTRY_PASSWORD}} | docker login ${{vars.CI_REGISTRY_HOST}} -u ${{vars.CI_REGISTRY_USERNAME}} --password-stdin
